In [5]:
import pandas as pd

In [25]:
employee_compensation = pd.read_csv("Compensation of employees and its components by industry (IT1,92_1225_DF_DCCN_ANA1_2,1.0).csv",encoding="utf-8-sig", quotechar="'", on_bad_lines="skip")
employee_compensation = employee_compensation[employee_compensation["BRKDW_INDUSTRY_NACE_REV2"] == "_T"][["TIME_PERIOD", "Observation"]].rename(columns={"Observation": "compensation_euros"})
employee_compensation

      TIME_PERIOD  compensation_euros
0            2016            665223.5
1            2017            682754.8
2            2018            703650.4
3            2019            718956.8
4            2020            677961.2
...           ...                 ...
3035         2020             12367.9
3036         2021             13714.1
3037         2022             16278.6
3038         2023             15148.2
3039         2024             15870.6

[68 rows x 2 columns]

In [24]:
value_added  = pd.read_csv("Output and value added by industry (IT1,92_1225_DF_DCCN_ANA1_1,1.0).csv", encoding="utf-8-sig", on_bad_lines="skip")
value_added   = value_added[value_added["BRKDW_INDUSTRY_NACE_REV2"] == "_T"][["TIME_PERIOD", "Observation"]].rename(columns={"Observation": "gross_value_added_euros"})
value_added

      TIME_PERIOD  gross_value_added_euros
0            2016                3260318.6
1            2017                3353545.8
2            2018                3395738.2
3            2019                3408472.1
4            2020                3143279.3
...           ...                      ...
8959         2021                1607816.2
8960         2022                1702253.6
8961         2023                1783264.3
8962         2024                1900954.9
8963         2025                1938607.4

[432 rows x 2 columns]

In [27]:
gdp_supply_side  = pd.read_csv("Gross domestic product supply side (IT1,93_498_DF_DCCN_PILT_1,1.0).csv", encoding="utf-8-sig", on_bad_lines="skip")
gdp_supply_side  = gdp_supply_side[gdp_supply_side["REF_AREA"] == "IT"][["TIME_PERIOD", "Observation"]].rename(columns={"Observation": "gdp_euros"})
gdp_supply_side

   TIME_PERIOD  gdp_euros
0         2015  1663277.7
1         2016  1704856.7
2         2017  1744493.0
3         2018  1777744.4
4         2019  1804066.8
5         2020  1670011.9
6         2021  1842507.4
7         2022  1998072.6
8         2023  2142601.7
9         2024  2199619.4

In [19]:
world_bank  = pd.read_csv("World_Bank_Econ.csv", encoding="utf-8-sig")
world_bank

,FREQ,FREQ_LABEL,REF_AREA,REF_AREA_LABEL,INDICATOR,INDICATOR_LABEL,UNIT_MEASURE,UNIT_MEASURE_LABEL,DATABASE_ID,DATABASE_ID_LABEL,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,A,Annual,ABW,Aruba,WB_CCDFS_DEBTDUEY,Central government debt maturing in 12 months ...,PT,Percentage,WB_CCDFS,A Cross-Country Database of Fiscal Space,...,2.796921,0.333214,1.083226,1.075603,1.678525,1.398046,1.348645,3.282532,2.707058,2.369535
1,A,Annual,ABW,Aruba,WB_CCDFS_FBMA,"Fiscal balance, % of 10-year moving average GDP",PT,Percentage,WB_CCDFS,A Cross-Country Database of Fiscal Space,...,-6.446430,-7.966341,-1.634916,-1.593364,-2.891918,-3.079565,-0.285148,-14.299284,-9.635033,-0.541551
2,A,Annual,ABW,Aruba,WB_CCDFS_FBY,"Fiscal balance, % of GDP",PT,Percentage,WB_CCDFS,A Cross-Country Database of Fiscal Space,...,-6.048000,-7.459000,-1.475000,-1.455000,-2.587000,-2.641000,-0.243000,-16.230000,-9.161000,-0.465000
3,A,Annual,ABW,Aruba,WB_CCDFS_GGDMA,"General government gross debt, % of 10-year mo...",PT,Percentage,WB_CCDFS,A Cross-Country Database of Fiscal Space,...,74.645564,83.005679,82.219094,82.555968,84.762163,85.483871,83.377121,98.975189,107.084439,104.945632
4,A,Annual,ABW,Aruba,WB_CCDFS_GGDY,"General government gross debt, % of GDP",PT,Percentage,WB_CCDFS,A Cross-Country Database of Fiscal Space,...,70.032000,77.709000,74.177000,75.387000,75.825000,73.310000,71.053000,112.339000,101.816000,90.111000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3370,A,Annual,ZWE,Zimbabwe,WB_CCDFS_STDEBTALL,"Short-term external debt stocks, % of total",PT,Percentage,WB_CCDFS,A Cross-Country Database of Fiscal Space,...,32.636767,31.570034,31.849468,27.393202,29.775457,26.807020,28.752587,30.224142,27.190692,NaN
3371,A,Annual,ZWE,Zimbabwe,WB_CCDFS_STDEBTRES,"Short-term external debt stocks, % of reserves",PT,Percentage,WB_CCDFS,A Cross-Country Database of Fiscal Space,...,578.450011,725.270846,707.061644,771.444210,1273.252040,3891.554379,2328.310564,11529.869386,445.367863,NaN
3372,A,Annual,ZWE,Zimbabwe,WB_CCDFS_XTDEBTRES,"Total external debt stocks, % of reserves",PT,Percentage,WB_CCDFS,A Cross-Country Database of Fiscal Space,...,1772.387625,2297.339440,2220.010832,2816.188492,4276.179731,14516.922755,8097.742804,38147.880109,1637.942371,NaN
3373,A,Annual,ZWE,Zimbabwe,WB_CCDFS_XTDEBTRXG,"Total external debt stocks, % of reserves excl...",PT,Percentage,WB_CCDFS,A Cross-Country Database of Fiscal Space,...,1774.203247,2300.416472,2307.273588,2819.385956,4283.828716,14603.671157,8130.739227,39900.732457,1641.953936,NaN
3374,A,Annual,ZWE,Zimbabwe,WB_CCDFS_XTDEBTY,"Total external debt stocks, % of GDP",PT,Percentage,WB_CCDFS,A Cross-Country Database of Fiscal Space,...,44.090958,42.866170,48.314178,55.788515,58.513026,34.082957,47.022719,47.364086,38.173762,NaN

In [30]:
year_cols = [c for c in world_bank.columns if c.isdigit()]
world_bank = world_bank[world_bank["REF_AREA"] == "ITA"].melt(id_vars=["INDICATOR"], value_vars=year_cols, var_name="TIME_PERIOD", value_name="value")
world_bank = world_bank.pivot_table(index="TIME_PERIOD", columns="INDICATOR", values="value").reset_index()
world_bank["TIME_PERIOD"] = world_bank["TIME_PERIOD"].astype(int)

KeyError: 'REF_AREA'

In [ ]:
merged = employee_compensation.merge(value_added, on="TIME_PERIOD", how="outer")

      TIME_PERIOD  compensation_euros  gross_value_added_euros
0            2016            665223.5                3260318.6
1            2016            665223.5                3260318.6
2            2016            665223.5                3260318.6
3            2016            665223.5                3260318.6
4            2016            665223.5                3237783.9
...           ...                 ...                      ...
3175         2025            900444.3                1720348.7
3176         2025            900444.3                2014632.8
3177         2025            900444.3                1977306.8
3178         2025            900444.3                1976737.7
3179         2025            900444.3                1938607.4

[3180 rows x 3 columns]

In [ ]:
merged = merged.merge(gdp_supply_side, on="TIME_PERIOD", how="outer")

,TIME_PERIOD,compensation_euros,gross_value_added_euros,gdp_euros_x,gdp_euros_y
0,2015,NaN,NaN,1663277.7,1663277.7
1,2016,665223.5,3260318.6,1704856.7,1704856.7
2,2016,665223.5,3260318.6,1704856.7,1704856.7
3,2016,665223.5,3260318.6,1704856.7,1704856.7
4,2016,665223.5,3260318.6,1704856.7,1704856.7
...,...,...,...,...,...
3176,2025,900444.3,1720348.7,NaN,NaN
3177,2025,900444.3,2014632.8,NaN,NaN
3178,2025,900444.3,1977306.8,NaN,NaN
3179,2025,900444.3,1976737.7,NaN,NaN
3180,2025,900444.3,1938607.4,NaN,NaN

In [38]:
merged = merged.merge(world_bank, on="TIME_PERIOD", how="outer")
merged

,TIME_PERIOD,compensation_euros,gross_value_added_euros,gdp_euros_x,gdp_euros_y,WB_CCDFS_AVGLIFE_x,WB_CCDFS_CBY_x,WB_CCDFS_DEBTDUEY_x,WB_CCDFS_DFFB_x,WB_CCDFS_DFGGD_x,...,WB_CCDFS_PBY_y,WB_CCDFS_PRDEBTY_y,WB_CCDFS_PSCY_y,WB_CCDFS_SECNRES_y,WB_CCDFS_SOVRATE_y,WB_CCDFS_STDEBTALL_y,WB_CCDFS_STDEBTRES_y,WB_CCDFS_XTDEBTRES_y,WB_CCDFS_XTDEBTRXG_y,WB_CCDFS_XTDEBTY_y
0,1990,NaN,NaN,NaN,NaN,NaN,-12.076512,NaN,-39.401628,359.701808,...,-1.783,NaN,68.0,NaN,20.500000,NaN,NaN,NaN,NaN,NaN
1,1991,NaN,NaN,NaN,NaN,NaN,-11.645166,NaN,-39.193341,372.428523,...,-0.472,NaN,70.4,NaN,20.247945,NaN,NaN,NaN,NaN,NaN
2,1992,NaN,NaN,NaN,NaN,NaN,-10.034919,NaN,-35.677166,399.512950,...,1.307,NaN,74.5,NaN,19.614754,NaN,NaN,NaN,NaN,NaN
3,1993,NaN,NaN,NaN,NaN,NaN,-8.413320,NaN,-34.490987,438.907518,...,2.068,NaN,74.9,NaN,18.252054,NaN,NaN,NaN,NaN,NaN
4,1994,NaN,NaN,NaN,NaN,NaN,-7.829716,NaN,-31.232524,462.691118,...,1.518,NaN,71.5,NaN,18.333333,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3201,2025,900444.3,1720348.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3202,2025,900444.3,2014632.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3203,2025,900444.3,1977306.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3204,2025,900444.3,1976737.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3205,2025,900444.3,1938607.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [39]:
merged.to_csv("italy_economic_data.csv", index=False)